name: My Blog
url: "https://oksanalutsyk.github.io/jekyll-blog"
baseurl: "/jekyll-blog"
sass:
  sass_dir: _sass
plugins:
  - jekyll-feed
  - jekyll-admin

jekyll_admin:
  - staticfiles
  - datafiles
  - configuration
